"""
Background work themes. Each theme yields the factual content a narrative must
convey. Variety here is what keeps 2,200 routine narratives from reading as
templated, so the library is deliberately large and the briefs carry slots that
get filled with per-work-order specifics.

Fields:
  key, wo_type, weight, asset_kind, res_codes (weighted), parts (or None),
  hours (lo, hi), brief templates
Region/season gating is applied by the scheduler, not here.
"""

# asset_kind: inverter | string_inverter | combiner | tracker | xfmr | bess |
#             met | site | module | mv | none

THEMES = [
    # ---------------------------------------------------------------- PM
    dict(key="pm_torque", wo_type="PM", weight=46, asset_kind="site",
         res=[("ADJUSTED", 4), ("OTHER", 2), ("NO-FAULT-FOUND", 1)],
         parts=None, hours=(3, 9),
         briefs=["Quarterly torque check on module clamps in {block}. {n} clamps found below spec, retorqued to 18 Nm. Rest sampled OK.",
                 "Torque audit {block}, sampled {n} rack bolts, all within tolerance.",
                 "Module clamp torque sweep {block}. Found a run of loose clamps on the east rows, retorqued."]),
    dict(key="pm_combiner", wo_type="PM", weight=52, asset_kind="combiner",
         res=[("NO-FAULT-FOUND", 4), ("CLEANED", 2), ("ADJUSTED", 2), ("PART-REPL", 1)],
         parts=["fuse 15A", None, None, "terminal lugs"], hours=(2, 6),
         briefs=["Annual cb inspection {asset}. Torqued lugs, IR scan clean, no hot spots.",
                 "{asset} PM. Found dust ingress on the lower gland, cleaned and resealed. Fuses all good.",
                 "Combiner PM {asset}, IR scan showed nothing, string currents balanced per SCADA."]),
    dict(key="pm_inverter", wo_type="PM", weight=58, asset_kind="inverter",
         res=[("CLEANED", 4), ("NO-FAULT-FOUND", 3), ("ADJUSTED", 2), ("PART-REPL", 1), ("SW-UPDATE", 1)],
         parts=[None, None, "air filter set", "cooling fan"], hours=(3, 8),
         briefs=["Semiannual PM on {asset}. Filters replaced, cabinet vacuumed, torque check on DC bus. No issues.",
                 "{asset} PM complete. Filters were loaded, swapped them. Fan bank tested ok, all six running.",
                 "PM {asset}. Cleaned heat sinks, checked contactors for pitting, none found. Logged and closed."]),
    dict(key="pm_xfmr", wo_type="PM", weight=26, asset_kind="xfmr",
         res=[("NO-FAULT-FOUND", 4), ("OTHER", 2), ("ESCALATED", 1)],
         parts=None, hours=(3, 7),
         briefs=["Oil sample pulled from {asset} and shipped for DGA. Bushings visually ok, no weeping.",
                 "{asset} annual. Checked LTC counter, gas relay clear, cleaned bushings."]),
    dict(key="pm_gfault", wo_type="PM", weight=30, asset_kind="combiner",
         res=[("NO-FAULT-FOUND", 5), ("ADJUSTED", 2), ("ESCALATED", 1)],
         parts=None, hours=(2, 6),
         briefs=["Ground fault continuity testing {block}. All readings within range.",
                 "GF testing on {asset} and adjacent. Megger readings normal, nothing to report."]),
    dict(key="pm_tracker", wo_type="PM", weight=44, asset_kind="tracker",
         res=[("ADJUSTED", 4), ("CLEANED", 1), ("PART-REPL", 2), ("NO-FAULT-FOUND", 2)],
         parts=[None, None, "grease cartridge", "u-bolt kit"], hours=(4, 11),
         briefs=["Tracker PM {asset}. Greased bearings, checked damper bolts, two were loose, retorqued.",
                 "{asset} lubrication and fastener check. Nothing unusual.",
                 "Annual tracker service {asset}, greased slew drive, checked backlash, within spec."]),
    dict(key="pm_met", wo_type="PM", weight=16, asset_kind="met",
         res=[("CLEANED", 4), ("ADJUSTED", 2), ("PART-REPL", 1)],
         parts=[None, "pyranometer", None], hours=(1, 4),
         briefs=["{asset} cleaned pyranometers and rain gauge, releveled the RSR.",
                 "Soiling station {asset} cleaned, reference cell wiped, data looked stuck so power cycled the logger."]),
    dict(key="pm_bess", wo_type="PM", weight=18, asset_kind="bess",
         res=[("NO-FAULT-FOUND", 4), ("CLEANED", 2), ("SW-UPDATE", 1), ("ADJUSTED", 1)],
         parts=None, hours=(3, 8),
         briefs=["Quarterly BESS PM {asset}. HVAC filters swapped, module voltages balanced, no alarms.",
                 "{asset} inspection, checked coolant loop and door seals, all fine."]),
    dict(key="pm_stringinv", wo_type="PM", weight=22, asset_kind="string_inverter",
         res=[("CLEANED", 3), ("NO-FAULT-FOUND", 3), ("PART-REPL", 1)],
         parts=[None, None, "fan module"], hours=(2, 5),
         briefs=["PM sweep on string inverters {block}. Cleaned intakes on {n} units, one had a noisy fan, tagged for follow up.",
                 "{asset} PM, heat sink cleaned, firmware checked, no faults in log."]),
    dict(key="pm_wash", wo_type="PM", weight=34, asset_kind="site",
         res=[("CLEANED", 8), ("OTHER", 1)],
         parts=None, hours=(6, 20),
         briefs=["Module wash {block}. Two truck crew, deionized water. Output up about {pct}% next clear day per SCADA.",
                 "Washing crew completed {block}. Ag dust was heavy on the lower rows.",
                 "Scheduled wash {block}, finished ahead of the wind advisory."]),

    # ------------------------------------------------------------ Inspection
    dict(key="insp_ir_aerial", wo_type="Inspection", weight=24, asset_kind="site",
         res=[("NO-FAULT-FOUND", 4), ("ESCALATED", 2), ("OTHER", 2)],
         parts=None, hours=(4, 9),
         briefs=["Aerial IR survey {block}. {n} hot cells flagged, scattered, nothing clustered. Report to asset manager.",
                 "Drone IR flight over {block}. Found two open strings, ticketed separately. Rest looked normal."]),
    dict(key="insp_walk", wo_type="Inspection", weight=30, asset_kind="site",
         res=[("NO-FAULT-FOUND", 5), ("OTHER", 2), ("ESCALATED", 1)],
         parts=None, hours=(2, 7),
         briefs=["Quarterly site walk {block}. Some cable sag on the north rows, will schedule.",
                 "Walkdown {block}, nothing significant. Two cracked modules noted for the punch list."]),
    dict(key="insp_storm", wo_type="Inspection", weight=20, asset_kind="site",
         res=[("NO-FAULT-FOUND", 4), ("ESCALATED", 2), ("OTHER", 2)],
         parts=None, hours=(3, 10),
         briefs=["Post event walkdown {block} after last night's weather. No structural damage found.",
                 "Storm walkdown, checked {block}, a few modules with cracked glass, tagged. Everything else looked fine."]),
    dict(key="insp_fence", wo_type="Inspection", weight=14, asset_kind="site",
         res=[("NO-FAULT-FOUND", 4), ("ADJUSTED", 2), ("PART-REPL", 1)],
         parts=[None, None, "fence fabric"], hours=(1, 5),
         briefs=["Perimeter inspection. Fence intact except a washout near the south gate, filled it.",
                 "Fence and gate check, camera 3 lens was fogged, wiped it down."]),
    dict(key="insp_soiling", wo_type="Inspection", weight=16, asset_kind="site",
         res=[("OTHER", 4), ("NO-FAULT-FOUND", 3), ("ESCALATED", 1)],
         parts=None, hours=(2, 5),
         briefs=["Soiling assessment {block}, soiling ratio around {pct}% per the reference cells. Recommending wash next cycle.",
                 "Walked {block} for soiling, dust accumulation moderate, not washing yet."]),

    # -------------------------------------------------------------------- CM
    dict(key="cm_inv_dcgf", wo_type="CM", weight=48, asset_kind="inverter",
         res=[("RESET", 3), ("PART-REPL", 3), ("NO-FAULT-FOUND", 2), ("ADJUSTED", 1)],
         parts=[None, "fuse 15A", "string connector", None], hours=(2, 9),
         briefs=["{asset} DC ground fault alarm. Isolated to {cb}, found a chafed home run against the rack. Repaired and returned to service.",
                 "Ground fault on {asset}, walked the strings, nothing obvious, meggered ok, reset and it held.",
                 "{asset} tripped DC GF. Traced to a pinched connector in {cb}. Replaced, back online."]),
    dict(key="cm_inv_acfault", wo_type="CM", weight=34, asset_kind="inverter",
         res=[("RESET", 4), ("NO-FAULT-FOUND", 3), ("VENDOR-REFERRED", 1), ("PART-REPL", 1)],
         parts=[None, None, "AC fuse", None], hours=(1.5, 7),
         briefs=["{asset} AC overcurrent trip. Reset, ran fine rest of the day. No pattern in the log.",
                 "Grid fault ride through event took {asset} offline, cleared on its own before I got there. Verified output normal.",
                 "{asset} down on AC undervoltage. POI looked normal. Reset and monitored two hours."]),
    dict(key="cm_inv_part", wo_type="CM", weight=30, asset_kind="inverter",
         res=[("PART-REPL", 5), ("VENDOR-REFERRED", 2), ("ESCALATED", 1)],
         parts=["DC bus capacitor", "IGBT module", "control board", "AC contactor",
                "gate driver", "DC contactor", "cooling fan"],
         hours=(4, 14),
         briefs=["{asset} hard fault, replaced {part}. Unit back online, no recurrence through end of shift.",
                 "Vendor walked me through diagnostics on {asset}, swapped the {part}. Took most of the day.",
                 "{asset} failed to start. Found {part} failed, replaced from site spares."]),
    dict(key="cm_inv_cooling", wo_type="CM", weight=22, asset_kind="inverter",
         res=[("CLEANED", 3), ("PART-REPL", 3), ("RESET", 2), ("NO-FAULT-FOUND", 1)],
         parts=[None, "cooling fan", "air filter set", None], hours=(2, 8),
         briefs=["{asset} cooling alarm. One fan seized, replaced it, others fine.",
                 "High cabinet temp on {asset}, filters were completely blocked. Cleaned, temp came back down.",
                 "{asset} flagged fan fault, found a bird nest in the intake plenum. Cleared it out."]),
    dict(key="cm_combiner", wo_type="CM", weight=44, asset_kind="combiner",
         res=[("PART-REPL", 5), ("NO-FAULT-FOUND", 2), ("ADJUSTED", 1), ("CLEANED", 1)],
         parts=["fuse 15A", "fuse 20A", None, "touch safe holder"], hours=(1.5, 6),
         briefs=["{asset} string {n} reading zero. Blown fuse, replaced, current came back.",
                 "Two fuses out in {asset}, replaced both. Checked for a cause, nothing found.",
                 "{asset} low current alarm, found water in the bottom of the enclosure. Drained, resealed gland, replaced one fuse."]),
    dict(key="cm_tracker_motor", wo_type="CM", weight=40, asset_kind="tracker",
         res=[("PART-REPL", 5), ("RESET", 2), ("ADJUSTED", 2)],
         parts=["tracker motor", "gearbox", None, "limit switch"], hours=(3, 10),
         briefs=["{asset} stuck at {ang} degrees. Motor drawing high current, replaced it. Row tracking again.",
                 "{asset} not following. Controller reset didn't take, swapped the {part}.",
                 "Row {asset} out of alignment with the rest of the block. Recalibrated limits, tracking normal now."]),
    dict(key="cm_tracker_ctrl", wo_type="CM", weight=32, asset_kind="tracker",
         res=[("RESET", 5), ("NO-FAULT-FOUND", 3), ("PART-REPL", 1), ("SW-UPDATE", 1)],
         parts=[None, None, "TCU board", None], hours=(1, 5),
         briefs=["{asset} controller offline. Power cycled the TCU, came back and tracked normally.",
                 "{asset} showing comm fault at the zone controller. Reseated the daisy chain, cleared.",
                 "Tracker fault {asset}, no fault when I got there, everything tracking. Reset the flag."]),
    dict(key="cm_scada", wo_type="CM", weight=42, asset_kind="site",
         res=[("RESET", 5), ("NO-FAULT-FOUND", 3), ("PART-REPL", 1), ("SW-UPDATE", 1)],
         parts=[None, None, "media converter", "patch cable"], hours=(1, 6),
         briefs=["Lost SCADA on {block}. Fiber run tested bad between the skid and {block}, patched around it, will schedule a permanent fix.",
                 "Data gap overnight. RTU had locked up, rebooted, points came back.",
                 "Comms alarm, everything was online when I arrived. Historian gap only, no production impact."]),
    dict(key="cm_mv", wo_type="CM", weight=20, asset_kind="mv",
         res=[("PART-REPL", 3), ("ESCALATED", 3), ("VENDOR-REFERRED", 2)],
         parts=["MV termination kit", None, "elbow connector"], hours=(5, 16),
         briefs=["MV cable fault between {block} and the collector. Locator put it about 300 ft in. Contractor scheduled.",
                 "Feeder relay tripped on {block}. Found a failed termination in the switchgear, replaced."]),
    dict(key="cm_module", wo_type="CM", weight=34, asset_kind="module",
         res=[("PART-REPL", 4), ("OTHER", 2), ("NO-FAULT-FOUND", 1)],
         parts=["module", None, "MC4 connector"], hours=(2, 7),
         briefs=["{n} broken modules in {block}, replaced from spares. Cause looked like rock strike from mowing.",
                 "Burned connector on a home run in {block}. Cut back and reterminated.",
                 "String out in {block}, found a module with a shattered cell area, swapped it."]),
    dict(key="cm_wiring", wo_type="CM", weight=24, asset_kind="site",
         res=[("ADJUSTED", 4), ("PART-REPL", 2), ("OTHER", 2)],
         parts=[None, "cable ties", "cable clips"], hours=(2, 8),
         briefs=["Cable management repair {block}. Wire runs had dropped into the mow path, resecured about {n} spans.",
                 "Reworked sagging home runs {block} before mowing gets there."]),
    dict(key="cm_bess", wo_type="CM", weight=16, asset_kind="bess",
         res=[("RESET", 3), ("PART-REPL", 2), ("VENDOR-REFERRED", 2), ("ESCALATED", 1)],
         parts=[None, "HVAC compressor", "module fuse"], hours=(3, 12),
         briefs=["{asset} module fault, isolated the string and called it in to the OEM.",
                 "BESS HVAC alarm on {asset}, compressor short cycling. Vendor coming out.",
                 "{asset} went to standby overnight. Cleared the alarm, back in service."]),
    dict(key="cm_met", wo_type="CM", weight=12, asset_kind="met",
         res=[("PART-REPL", 3), ("RESET", 2), ("CLEANED", 2)],
         parts=["pyranometer", None, "anemometer"], hours=(1, 4),
         briefs=["{asset} irradiance reading flatlined. Sensor failed, swapped it.",
                 "Wind sensor on {asset} reading zero in obvious wind. Bearing shot, replaced."]),
    dict(key="cm_stringinv", wo_type="CM", weight=26, asset_kind="string_inverter",
         res=[("RESET", 4), ("PART-REPL", 2), ("NO-FAULT-FOUND", 2), ("SW-UPDATE", 1)],
         parts=[None, None, "string inverter", "fan module"], hours=(1.5, 6),
         briefs=["{asset} offline. Reset at the disconnect, came back up.",
                 "{asset} showing isolation fault. Damp morning, cleared once it dried out.",
                 "Swapped {asset} for a spare, RMA the old one."]),

    # ------------------------------------------------------------- Emergency
    dict(key="em_poi", wo_type="Emergency", weight=12, asset_kind="mv",
         res=[("RESET", 3), ("ESCALATED", 3), ("VENDOR-REFERRED", 1)],
         parts=None, hours=(4, 16),
         briefs=["POI breaker tripped, whole plant down. Utility said it was on their side. Restored after coordination, about {hrs} hours off.",
                 "Site trip overnight. Relay targets pointed at the main feeder. Walked the collector, nothing visible, restored under supervision."]),
    dict(key="em_animal", wo_type="Emergency", weight=10, asset_kind="site",
         res=[("PART-REPL", 3), ("CLEANED", 2), ("OTHER", 2)],
         parts=["fuse 15A", None, "cable"], hours=(2, 8),
         briefs=["Outage on {block}, found a snake across the bus in the skid. Cleaned up, replaced what was damaged.",
                 "Coyote dug under the fence and chewed a home run in {block}. Repaired, patched the fence."]),
    dict(key="em_storm", wo_type="Emergency", weight=12, asset_kind="site",
         res=[("ESCALATED", 3), ("PART-REPL", 2), ("OTHER", 3)],
         parts=None, hours=(5, 18),
         briefs=["Called out after the storm. Water in two combiner skids in {block}, isolated them and pumped out.",
                 "Lightning took out the comms and a surge card overnight. Restored partial monitoring, rest tomorrow."]),
    dict(key="em_fire", wo_type="Emergency", weight=5, asset_kind="site",
         res=[("ESCALATED", 4), ("VENDOR-REFERRED", 2), ("OTHER", 1)],
         parts=None, hours=(4, 14),
         briefs=["Smoke reported at the {block} skid. No fire on arrival, heavy discoloration on one MV termination. Isolated and locked out pending engineering.",
                 "Grass fire along the south fence, FD handled it. Checked the array, no damage to modules."]),

    # ------------------------------------------------------------- Vegetation
    dict(key="veg_mow", wo_type="Vegetation", weight=54, asset_kind="site",
         res=[("OTHER", 5), ("CLEANED", 2), ("ADJUSTED", 1)],
         parts=None, hours=(6, 26),
         briefs=["Mowing {block}. Growth was ahead of schedule after the rain, took an extra day.",
                 "Mow crew on site {block}, reminded them about the home runs in the rows.",
                 "Completed mowing {block}. Two rows skipped, ground too soft."]),
    dict(key="veg_spray", wo_type="Vegetation", weight=26, asset_kind="site",
         res=[("OTHER", 5), ("CLEANED", 1)],
         parts=["herbicide", None], hours=(5, 14),
         briefs=["Spray application {block}, pre emergent. Wind was borderline, held off on the west edge.",
                 "Herbicide {block} per the plan. Buffer maintained at the drainage.",
                 "Sprayed {block}. Had to stop early, wind picked up after lunch. Rest tomorrow.",
                 "Post emergent on {block}, spot treated the fence line. Records in the binder."]),
    dict(key="veg_tree", wo_type="Vegetation", weight=18, asset_kind="site",
         res=[("OTHER", 4), ("ESCALATED", 1)],
         parts=None, hours=(6, 20),
         briefs=["Tree line trimming on the east boundary. Shading on the first two rows in the morning, cut it back.",
                 "Cleared volunteer growth along the fence {block}, several were into the fabric.",
                 "Trimmed back the treeline south of {block}. Contractor left the brush, chasing them on it.",
                 "Brush clearing {block}. Heavier than the last cycle, the wet spring got ahead of us."]),

    # --------------------------------------------------------------- Warranty
    dict(key="wty_module", wo_type="Warranty", weight=14, asset_kind="module",
         res=[("VENDOR-REFERRED", 5), ("PART-REPL", 2), ("ESCALATED", 1)],
         parts=["module", None], hours=(2, 8),
         briefs=["Pulled {n} modules from {block} for the warranty claim, boxed and staged for pickup. Photos in the file.",
                 "Warranty replacement modules arrived, installed in {block}. Old ones on the pallet for RMA.",
                 "{n} modules from {block} flagged for the claim. Serials recorded, EL images attached.",
                 "Installed the warranty modules in {block}. Torqued and re-strung, string current back to normal."]),
    dict(key="wty_inverter", wo_type="Warranty", weight=14, asset_kind="inverter",
         res=[("VENDOR-REFERRED", 5), ("PART-REPL", 2), ("ESCALATED", 1)],
         parts=[None, "control board", "DC bus capacitor"], hours=(3, 11),
         briefs=["Warranty part for {asset} came in, installed with the vendor on the phone. Old part going back.",
                 "{asset} still under parts warranty, opened a case with the OEM, waiting on the RMA.",
                 "{asset} claim approved, part arrived today. Swapped it out, unit back in service.",
                 "Opened a warranty case on {asset}. OEM wants fault logs before they authorise anything.",
                 "{asset} warranty swap done. Took two trips, the first part was damaged in shipping."]),
    dict(key="wty_tracker", wo_type="Warranty", weight=10, asset_kind="tracker",
         res=[("VENDOR-REFERRED", 4), ("PART-REPL", 3)],
         parts=["gearbox", "tracker motor", None], hours=(3, 9),
         briefs=["Warranty gearbox for {asset} installed, OEM tech observed remotely.",
                 "Submitted warranty claim on {asset}, drive was inside the coverage window.",
                 "{asset} drive failed at {n} months, well inside warranty. Claim filed, OEM wants the old unit back.",
                 "Replaced {asset} motor under warranty. Paperwork and serial photos uploaded.",
                 "{asset} warranty repair. OEM shipped the wrong revision first time, second one fit."]),

    # ------------------------------------------------------------------ misc
    dict(key="misc_vandal", wo_type="CM", weight=8, asset_kind="site",
         res=[("PART-REPL", 3), ("ESCALATED", 2), ("OTHER", 2)],
         parts=["fence fabric", "cable", None], hours=(3, 10),
         briefs=["Copper theft attempt at {block}. Cut fence, some grounding conductor taken. Filed a report, repaired.",
                 "Vandalism, several modules shot out along the road side. Documented and replaced {n}."]),
    dict(key="misc_safety", wo_type="Inspection", weight=6, asset_kind="site",
         res=[("OTHER", 4), ("ESCALATED", 2)],
         parts=None, hours=(1, 4),
         briefs=["Near miss reported. Contractor entered {block} without checking in for the LOTO on the skid. Stood the crew down and rebriefed.",
                 "Near miss, loose grating at the {block} skid entry, someone nearly went through. Secured it and tagged for repair."]),
    dict(key="misc_dup", wo_type="CM", weight=7, asset_kind="none",
         res=[("OTHER", 4), ("NO-FAULT-FOUND", 4)],
         parts=None, hours=(0.25, 1.5),
         briefs=["Duplicate, see the other ticket for the same alarm.",
                 "Opened in error.",
                 "Wrong site, closing."]),
    dict(key="misc_snow", wo_type="CM", weight=10, asset_kind="site",
         res=[("CLEANED", 3), ("OTHER", 3), ("ADJUSTED", 2)],
         parts=None, hours=(3, 12),
         briefs=["Snow clearing on the access roads and skid pads {block}. Array left to shed on its own.",
                 "Rows stowed flat under snow load per procedure, released them once it cleared."]),
]
